name: watermelon_game
description: "Watermelon Game"

publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.29.0
  flame_forge2d: ^0.19.0+2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/fruit/blueberry.png
    - assets/images/fruit/strawberry.png
    - assets/images/fruit/orange.png
    - assets/images/fruit/lime.png
    - assets/images/fruit/peach.png
    - assets/images/fruit/apple.png
    - assets/images/fruit/coconut.png
    - assets/images/fruit/pomegranate.png
    - assets/images/fruit/cantaloupe.png
    - assets/images/fruit/watermelon.png
    - assets/images/background.png

  fonts:
    - family: The Fruit Star
      fonts:
        - asset: assets/fonts/The Fruit Star.ttf